Changed write barriers to use int-based comparisons rather than VM_Address as this was causing the opt compiler to crash:
com.ibm.JikesRVM.opt.OPT_OptimizingCompilerException: erroneous computation: v1(<null>) this(>=U) v2(Addr 1912602624)
        at com.ibm.JikesRVM.opt.ir.OPT_ConditionOperand.evaluate(OPT_ConditionOperand.java:346)
        at com.ibm.JikesRVM.opt.OPT_Simplifier.simplify(OPT_Simplifier.java(Compiled Code))
        at com.ibm.JikesRVM.opt.OPT_Simple.foldConstants(OPT_Simple.java(Compiled Code))
        at com.ibm.JikesRVM.opt.OPT_Simple.perform(OPT_Simple.java:123)
        at com.ibm.JikesRVM.opt.OPT_ExpandRuntimeServices.perform(OPT_ExpandRuntimeServices.java:460)